parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/DependencyInjection/'
            - '../src/Infrastructure/Entity/'
            - '../src/Infrastructure/Kernel.php'
